[package]
name = "byte_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
lazy_static = "1.4.0"
serde = { version = "1.0.152", features = ["derive"] }

[build-dependencies]
uneval = "0.2.4"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
